### ISSUE TITLE
Wrong selection after inserting number sequence

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [qcz/vscode-text-power-tools#80] opened 2024-01-27 20:19 UTC
https://github.com/qcz/vscode-text-power-tools/assets/39968/0b07d752-2f15-4ecb-ac66-a22047ab6a10

**Comment by qcz** [comment] 2024-03-17 11:42
I am not able to reproduce this bug in version 1.87.2, so it was probably a bug in VSCode itself or caused by an other extension.

Please let me know if you still have this problem.

**Comment by qcz** [comment] 2024-07-18 09:19
No further info received, closing.

**Closed by qcz** 2024-07-18 09:19 UTC
Labels: further info needed
